server:
  port: 7002
  servlet:
    context-path: /coupon-distribution

spring:
  application:
    name: eureka-client-coupon-distribution
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coupon_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: admin
    password: adminadmin
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: MiniCouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # password:
    timeout: 10000
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: imooc-coupon-x
      auto-offset-reset: latest
  # Enable Ribbon retry mechanism and try to get service from other node if failed in the first place
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8001/eureka/

logging:
  level:
    com.imooc.coupon: debug

feign:
  hystrix:
    enabled: true   # Hystrix by default disabled
  client:
    config:
      default:  # global config
        connectTimeout: 2000  # default timeout is 10000(10s)
        readTimeout: 5000
      eureka-client-coupon-template:  # task specific config
        connectTimeout: 3000  # default timeout is 10000(10s)
        readTimeout: 5000
